version: "3.9"
services:
  backend:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - ENV=production
      - HTTP_ADRESS=0.0.0.0:8090
    ports:
      - "${HTTP_ADRESS}:8090"
    networks:
      - roadmapik

networks:
  roadmapik:
    name: roadmapik
    external: true
