name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.REGISTRY_TOKEN}}
    
    - name: 'Build and Push Backend Image'
      run: |
        docker build --cache-from ghcr.io/smart7even/backend:latest . --tag ghcr.io/smart7even/backend:latest
        docker push ghcr.io/smart7even/backend:latest
